#! /usr/bin/env zsh

# ready to stow
cd ~/.dot

# basics
stow --adopt $1 emacs gpg git stack vim zsh

# linux (i3+xfce4)
if [[ ! $+WSL ]]; then
    stow --adopt $1 \
        compton dunst fontconfig i3 i3blocks mpv onedrive \
        pulseaudio-ctl qutebrowser ranger variety xdg xfce4

    # omen laptop
    if [[ $(hostname) == "omen" ]]; then
        stow --adopt $1 nvidia-omen xfce4-omen
        sudo stow --adopt --target=/ $1 root-nvidia-omen
    fi
fi
