#! /usr/bin/env zsh

# stow options
STOW_OPTIONS=(--adopt --no-folding $@)

# ready to stow
cd ~/.dot

# basics
stow $STOW_OPTIONS emacs gpg git stack vim zsh

# linux (i3+xfce4)
if (( ! $+WSL )); then
    stow $STOW_OPTIONS \
        compton dunst fontconfig i3 i3blocks mpv onedrive \
        pulseaudio-ctl qutebrowser ranger variety xdg xfce4

    #sudo stow $STOW_OPTIONS --target=/ root-sshtunnel

    # omen laptop
    if [[ $(hostname) == "omen" ]]; then
        stow $STOW_OPTIONS nvidia-omen xfce4-omen
        sudo stow $STOW_OPTIONS --target=/ root-nvidia-omen
    fi
fi
